import React from 'react';
import { cn } from '../../lib/utils';

export function Panel({className,children,...rest}:React.HTMLAttributes<HTMLElement>){return <section {...rest} className={cn('relative flex min-w-0 flex-col overflow-hidden rounded-2xl border border-white/[0.08] bg-[#0a0a0a] shadow-[0_18px_55px_rgba(0,0,0,0.32),inset_0_1px_0_rgba(255,255,255,0.035)]',className)}>{children}</section>}
export function PanelHeader({className,children}:{className?:string;children:React.ReactNode}){return <div className={cn('flex flex-wrap items-center justify-between gap-3 border-b border-white/[0.06] bg-gradient-to-b from-white/[0.035] to-transparent px-4 py-4 sm:px-5',className)}>{children}</div>}
export function PanelTitle({as:Tag='h2',className,children}:{as?:'h2'|'h3'|'h4';className?:string;children:React.ReactNode}){return <Tag className={cn('flex min-w-0 items-center gap-2 text-sm font-semibold tracking-tight text-neutral-100',className)}>{children}</Tag>}
export function PanelSubtitle({children}:{children:React.ReactNode}){return <p className="mt-1 text-[11px] leading-relaxed text-neutral-600">{children}</p>}
export function PanelActions({className,children}:{className?:string;children:React.ReactNode}){return <div className={cn('flex flex-wrap items-center justify-end gap-1.5 sm:gap-2',className)}>{children}</div>}
export function PanelFooter({className,children}:{className?:string;children:React.ReactNode}){return <div className={cn('flex flex-wrap items-center gap-x-4 gap-y-2 border-t border-white/[0.06] px-4 py-3 text-[10px] font-mono text-neutral-600 sm:px-5',className)}>{children}</div>}
export function SectionHeading({icon:Icon,children,hint}:{icon?:React.ComponentType<any>;children:React.ReactNode;hint?:React.ReactNode}){return <div className="flex flex-wrap items-baseline justify-between gap-2 pt-1"><h2 className="flex items-center gap-2 text-[11px] font-mono font-medium uppercase tracking-[0.16em] text-neutral-400">{Icon?<Icon className="h-3.5 w-3.5 text-blue-400" aria-hidden/>:null}{children}</h2>{hint?<span className="text-[10px] font-mono uppercase tracking-wide text-neutral-700">{hint}</span>:null}</div>}
export function Chip({className,children,tone='signal',title}:{className?:string;children:React.ReactNode;tone?:'signal'|'neutral'|'positive'|'negative'|'warning';title?:string}){const t={signal:'border-blue-500/20 bg-blue-500/10 text-blue-400',neutral:'border-white/[0.08] bg-neutral-900 text-neutral-400',positive:'border-emerald-500/20 bg-emerald-500/10 text-emerald-400',negative:'border-red-500/20 bg-red-500/10 text-red-400',warning:'border-amber-500/20 bg-amber-500/10 text-amber-400'};return <span title={title} className={cn('inline-flex shrink-0 items-center rounded-full border px-2.5 py-1 text-[10px] font-mono tabular-nums uppercase tracking-wide',t[tone],className)}>{children}</span>}
